name: kobermart_client
version: 1.2.4+7
publish_to: none
description: Platform anggota Kober Bali Jaya
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  badges: ^2.0.3
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.3             
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  get: 4.6.5
  get_cli: ^1.8.1
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  sticky_grouped_list: ^3.1.0
  username_gen: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  assets:
    - assets/images/
    - assets/images/operator/
    - assets/logo/
    - assets/icons/
  uses-material-design: true
