name: kobermart_client
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  badges: ^2.0.3
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.4.5
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.2
  firebase_auth: ^3.4.1
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  get: 4.6.5
  get_cli: ^1.8.1
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  username_gen: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
  uses-material-design: true
