part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const SHOP = _Paths.SHOP;
  static const MEMBERS = _Paths.MEMBERS;
  static const TRANSACTIONS = _Paths.TRANSACTIONS;
  static const MENU = _Paths.MENU;
  static const CART = _Paths.CART;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const QRCODE = _Paths.QRCODE;
  static const REGISTRATION = _Paths.REGISTRATION;
  static const TOPUP = _Paths.TOPUP;
  static const TOKEN_REGISTRATION = _Paths.TOKEN_REGISTRATION;
  static const TOKENINPUT = _Paths.TOKENINPUT;
  static const NEWTOKEN = _Paths.NEWTOKEN;
  static const TOKENLIST = _Paths.TOKENLIST;
  static const MEMBERHISTORY = _Paths.MEMBERHISTORY;
  static const TOKENDETAIL = _Paths.TOKENDETAIL;
  static const MEMBERPROFILE = _Paths.MEMBERPROFILE;
  static const BALANCETRANSFER = _Paths.BALANCETRANSFER;
  static const TRANSFERNOMINAL = _Paths.TRANSFERNOMINAL;
  static const WITHDRAWAL = _Paths.WITHDRAWAL;
  static const PROFILE = _Paths.PROFILE;
  static const PRODUCT = _Paths.PRODUCT;
  static const BUYNOW = _Paths.BUYNOW;
  static const TRXDETAIL_SHOP = _Paths.TRXDETAIL_SHOP;
  static const TRXDETAIL_WITHDRAWAL = _Paths.TRXDETAIL_WITHDRAWAL;
  static const TRXDETAIL_TOPUP = _Paths.TRXDETAIL_TOPUP;
  static const TRXDETAIL_TRANSFER = _Paths.TRXDETAIL_TRANSFER;
  static const TRXDETAIL_CASHBACK = _Paths.TRXDETAIL_CASHBACK;
  static const TRXDETAIL_TOKEN = _Paths.TRXDETAIL_TOKEN;
  static const TRASHBANK = _Paths.TRASHBANK;
  static const INVESTMENT = _Paths.INVESTMENT;
  static const PPOB = _Paths.PPOB;
  static const TRXDETAIL_PREPAID = _Paths.TRXDETAIL_PREPAID;
  static const TRXDETAIL_POSTPAID = _Paths.TRXDETAIL_POSTPAID;
  static const CASHBACK_HISTORY = _Paths.CASHBACK_HISTORY;
  static const INPUTNUMBER = _Paths.INPUTNUMBER;
  static const SELECTMETHOD = _Paths.SELECTMETHOD;
  static const DIGITALPRODUCTS = _Paths.DIGITALPRODUCTS;
  static const PPOB_PULSADATA = _Paths.PPOB_PULSADATA;
  static const PPOB_PLN_PREPAID = _Paths.PPOB_PLN_PREPAID;
  static const PPOB_PLN_POSTPAID = _Paths.PPOB_PLN_POSTPAID;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const SHOP = '/shop';
  static const MEMBERS = '/members';
  static const TRANSACTIONS = '/transactions';
  static const MENU = '/menu';
  static const CART = '/cart';
  static const NOTIFICATION = '/notification';
  static const QRCODE = '/qrcode';
  static const REGISTRATION = '/registration';
  static const TOPUP = '/topup';
  static const TOKEN_REGISTRATION = '/token-registration';
  static const TOKENINPUT = '/tokeninput';
  static const NEWTOKEN = '/newtoken';
  static const TOKENLIST = '/tokenlist';
  static const MEMBERHISTORY = '/memberhistory';
  static const TOKENDETAIL = '/tokendetail';
  static const MEMBERPROFILE = '/memberprofile';
  static const BALANCETRANSFER = '/balancetransfer';
  static const TRANSFERNOMINAL = '/transfernominal';
  static const WITHDRAWAL = '/withdrawal';
  static const PROFILE = '/profile';
  static const PRODUCT = '/product';
  static const BUYNOW = '/buynow';
  static const TRXDETAIL_SHOP = '/trxdetail-shop';
  static const TRXDETAIL_WITHDRAWAL = '/trxdetail-withdrawal';
  static const TRXDETAIL_TOPUP = '/trxdetail-topup';
  static const TRXDETAIL_TRANSFER = '/trxdetail-transfer';
  static const TRXDETAIL_CASHBACK = '/trxdetail-cashback';
  static const TRXDETAIL_TOKEN = '/trxdetail-token';
  static const TRASHBANK = '/trashbank';
  static const INVESTMENT = '/investment';
  static const PPOB = '/ppob';
  static const TRXDETAIL_PREPAID = '/trxdetail-prepaid';
  static const TRXDETAIL_POSTPAID = '/trxdetail-postpaid';
  static const CASHBACK_HISTORY = '/cashback-history';
  static const INPUTNUMBER = '/inputnumber';
  static const SELECTMETHOD = '/selectmethod';
  static const DIGITALPRODUCTS = '/digitalproducts';
  static const PPOB_PULSADATA = '/ppob-pulsadata';
  static const PPOB_PLN_PREPAID = '/ppob-pln-prepaid';
  static const PPOB_PLN_POSTPAID = '/ppob-pln-postpaid';
}
